### ISSUE TITLE
All ai2html artboard images are loading

### ISSUE THREAD

**Issue by fcage** [reuters-graphics/ai2html#9]
The current ai2html implementation loads all of the artboard images rather than the image for the artbaord presented to the reader.

For example: https://graphics.reuters.com/CLIMATE-CHANGE/ICEBERG/yzdvxjrbzvx/index.html

If you view in the network tab in Chrome, all of the artboard image sizes are loading: sm, md, lg, xl.

What appears to happen: divs with background images are baked into the page via index.ejs. There's JS that fires to hide the unwanted artboard sizes but by that point the images have loaded. 

One possible quick solution could be to initially hide all of the artboards and let JS display the desired size -- basically the implementation now, but starting with al hidden rather than all displayed. This would continue to take advantage of background images not loading if the div is set to display none.

Thoughts, @hobbes7878 @manas271196 @chriscanipe?

**Comment by manas271196** [comment]
fixed. be great if someone else can test too.

**Comment by fcage** [comment]
I think I tested this before and forgot to comment. Problem solved.
